### ISSUE TITLE
Logging Sanity Checks

### ISSUE THREAD

**Issue by lapplislazuli** [Tritlo/Endemic#16]
Check for the logs the following

- [x] Is everything Logging, and no PrintLn
- [x] Sanity Check LogLevels
- [x] Do not  log our names / tool name
- [x] Make a visible and specified log with WallClockTime
- [x] Log also to a logfile

Maybe: Check if we have a logging-overhead depending on the loglevel and get a rough estimate in %?

**Comment by Tritlo** [comment]
This is now merged with #22 and #23
