### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by lapplislazuli** [Tritlo/Endemic#17]
We should have a 

- [x] Dockerfile to build the tool
- [x] A nice entrypoint that stitches the commandline params in 
- [ ] DockerImage here in the repo 
- [ ] A compose example (maybe on our test-examples) that 
  - [ ]    builds the tool 
  - [x]    mounts the project to repair
  - [ ]    mounts the output
  - [ ]    uses a configuration file

**Comment by lapplislazuli** [comment]
As shortly discussed in #20 , the program writes the .hi files in compilation. 
Hence, the mounted input volume currently needs to be read-write (as the .hi are written). 

To work around this, add a copy all to the entry point

- [ ] to entrypoint: Copy from /input to /tmp_input_copy where the compilation runs 
- [ ] use :ro on original /input

**Comment by lapplislazuli** [comment]
We should have 2 Dockerfiles: 
One that builds the program, and one that starts from the .exe. 

This enables us to provide an image that uses the "hidden" binary and does not leak source code (for anon reasons)

**Comment by Tritlo** [comment]
> We should have 2 Dockerfiles:
> One that builds the program, and one that starts from the .exe.
> 
> This enables us to provide an image that uses the "hidden" binary and does not leak source code (for anon reasons)

I like this approach.

> As shortly discussed in #20 , the program writes the .hi files in compilation.
> Hence, the mounted input volume currently needs to be read-write (as the .hi are written).
> 
> To work around this, add a copy all to the entry point
> 
> * [ ]  to entrypoint: Copy from /input to /tmp_input_copy where the compilation runs
> * [ ]  use :ro on original /input

I like this idea, but we have to be careful of what we copy. E.g. we should make sure we don't copy the `dist-newstyle` etc.

**Comment by lapplislazuli** [comment]
closed with #33 in commit 8935917f44cf . 

The second anonymized dockerfile will be done in the experiment repo (I think it rather belongs there). 

The `:ro` approach I do another day.
