### ISSUE TITLE
Deprecate/Rebrand old GenParts

### ISSUE THREAD

**Issue by lapplislazuli** [Tritlo/Endemic#19]
Currently, we still run with "Gen.hs" and "Gen2.hs".
We should clean this up while keeping the old things as bread first search.

- [x] Rename Gen.hs to BFS (or something similar)
- [x] Rename Gen2 to Gen
- [ ] Make a Switch in the Main which Search to Use
- [ ] Make an entry in the Configuration which search to use (Related #18)
- [x] Maybe: add a layer of modules for search, e.g. Endemic.Search which has Endemic.Search.Genetic & Endemic.Search.BFS

**Comment by Tritlo** [comment]
This is partially fixed, the switch will be fixed when we fix #18
