### ISSUE TITLE
What happens for the unnamed module?

### ISSUE THREAD

**Issue by lapplislazuli** [Tritlo/Endemic#63]
All our examples are currently in named modules. 

What happens if we use an unnamed module? 

Will we get a good error? 

If it "just works" - can we make a small test for it?

**Comment by Tritlo** [comment]
Most of our tests in `Tests.hs` are for unnamed modules, so it's pretty thoroughly tested! There's a caveat however: we  can't do data declarations in unnamed modules.

**Comment by Tritlo** [comment]
However: without a module it has to be provided using the `RProb` constructor

**Comment by Tritlo** [comment]
However, it has to be passed along with the `RProb` constructor. Most of what we do doesn't really work without a module

**Comment by Tritlo** [comment]
It starts off and works great, but then it runs into a linker error. I'd reccommend against running it without a module name without the `RProb` mechanism @lapplislazuli

**Comment by Tritlo** [comment]
It seems a bit worse than that: `GHC` says that `Main` is a reserved module name for the module you'll be exectuing in the package, and doesn't allow two of those.

**Comment by Tritlo** [comment]
Alright, we have a fix in 0cb7b0e, though we can't do data declarations in unnamed modules: GHC simply won't allow us to import from a module named Main without having an issue with the linker (this is probably a GHC bug)

**Comment by Tritlo** [comment]
Now it creates a fake module in this case and uses that.
